# Generated by Django 3.1.1 on 2020-10-11 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('auth_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('pub_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=20, unique=True)),
                ('auth', models.ManyToManyField(to='app_home.Author')),
                ('pub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_home.publish')),
            ],
        ),
    ]
