# Generated by Django 3.1.1 on 2020-10-10 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usr',
        ),
    ]
